(()=>{
'use strict';

const VERSION='1.2.0';
const AUTO_ITEMS=[
  {id:'scout',name:'斥候ドローン',icon:'🛸',rate:.5,unlock:0,desc:'2秒に1回、自動探索',base:{wood:40,stone:15},scale:1.18},
  {id:'crew',name:'探索班',icon:'🥾',rate:2,unlock:0,desc:'毎秒2回、自動探索',base:{wood:140,food:100},scale:1.19},
  {id:'rover',name:'自律ローバー',icon:'🤖',rate:10,unlock:1,desc:'毎秒10回、自動探索',base:{stone:400,knowledge:100},scale:1.20},
  {id:'satellite',name:'観測衛星',icon:'🛰️',rate:50,unlock:2,desc:'毎秒50回、自動探索',base:{stone:1500,knowledge:500},scale:1.21},
  {id:'swarm',name:'ドローン群',icon:'⚡',rate:250,unlock:3,desc:'毎秒250回、自動探索',base:{wood:5000,stone:5000,knowledge:3000},scale:1.22},
  {id:'worldai',name:'惑星AI',icon:'◇',rate:1000,unlock:4,desc:'毎秒1000回、自動探索',base:{knowledge:15000,stone:12000},scale:1.23}
];
const META={wood:{icon:'🌲',label:'木'},stone:{icon:'🪨',label:'石'},food:{icon:'🍎',label:'食料'},population:{icon:'👤',label:'人口'},knowledge:{icon:'✦',label:'知識'}};
const KEYS=Object.keys(META);
const SKILLS={
  moss:{name:'森の記憶',desc:'木の獲得量 +5%',mods:{wood:1.05}},
  seed:{name:'豊穣の種',desc:'食料の獲得量 +5%',mods:{food:1.05}},
  spring:{name:'生命の泉',desc:'人口の獲得量 +5%',mods:{population:1.05}},
  bird:{name:'追い風',desc:'手動探索の全獲得量 +10%',mods:{manual:1.10}},
  crystal:{name:'結晶共鳴',desc:'石の獲得量 +10%',mods:{stone:1.10}},
  fruit:{name:'月の実り',desc:'食料の獲得量 +10%',mods:{food:1.10}},
  ruins:{name:'考古眼',desc:'図鑑発見率 +20%',mods:{discovery:1.20}},
  fox:{name:'先導者',desc:'自動探索速度 +10%',mods:{autoRate:1.10}},
  map:{name:'未知への誘い',desc:'特殊イベント率 +25%',mods:{eventRate:1.25}},
  machine:{name:'旧文明の駆動系',desc:'自動探索速度 +20%',mods:{autoRate:1.20}},
  meteor:{name:'星屑ブースト',desc:'手動探索の全獲得量 +20%',mods:{manual:1.20}},
  archive:{name:'記憶増幅',desc:'知識の獲得量 +20%',mods:{knowledge:1.20}},
  core:{name:'惑星脈動',desc:'全資源の獲得量 +15%',mods:{all:1.15}},
  garden:{name:'眠らない庭',desc:'オフライン自動探索 +30%',mods:{offline:1.30}},
  signal:{name:'共鳴通信',desc:'イベント報酬 +25%',mods:{eventReward:1.25}},
  ai:{name:'星の演算',desc:'自動探索速度 +50%',mods:{autoRate:1.50}},
  gate:{name:'次元加速',desc:'全資源の獲得量 +30%',mods:{all:1.30}},
  origin:{name:'原初の祝福',desc:'全資源 +50% / 発見率 +50%',mods:{all:1.50,discovery:1.50}}
};
let autoCarry=0,lastTick=performance.now(),lastAutoFx=0,autoTimer=null,eventLocked=false,combo=0,lastManualAt=0;

function fmt2(n){const v=Math.floor(Number(n)||0);return v<1e6?v.toLocaleString('ja-JP'):v<1e9?`${(v/1e6).toFixed(v<1e7?1:0)}M`:`${(v/1e9).toFixed(v<1e10?1:0)}B`;}
function skillMods(){const m={wood:1,stone:1,food:1,population:1,knowledge:1,manual:1,all:1,autoRate:1,discovery:1,eventRate:1,offline:1,eventReward:1};(state.discovered||[]).forEach(id=>{const s=SKILLS[id];if(!s)return;Object.entries(s.mods).forEach(([k,v])=>m[k]*=v);});return m;}
function applyGain(key,value,mode='normal'){const m=skillMods();let mult=(m[key]||1)*m.all;if(mode==='manual')mult*=m.manual;if(mode==='event')mult*=m.eventReward;return Math.max(0,Math.round(value*mult));}
function baseRate(){return AUTO_ITEMS.reduce((sum,a)=>sum+(state.automation[a.id]||0)*a.rate,0);}
function rate(){return baseRate()*skillMods().autoRate;}
function totalAuto(){return Object.values(state.automation||{}).reduce((a,b)=>a+(Number(b)||0),0);}
function snap(){return Object.fromEntries(KEYS.map(k=>[k,state.resources[k]||0]));}
function diff(before){const d={};KEYS.forEach(k=>{const v=Math.round((state.resources[k]||0)-(before[k]||0));if(v)d[k]=v;});return d;}
function scaledCost(a){const lv=state.automation[a.id]||0,out={};Object.entries(a.base).forEach(([k,v])=>out[k]=Math.ceil(v*Math.pow(a.scale,lv)));return out;}
function afford(c){return Object.entries(c).every(([k,v])=>(state.resources[k]||0)>=v);}
function costText2(c){return Object.entries(c).map(([k,v])=>`${META[k].icon}${fmt2(v)}`).join(' ');}

function ensureState(){state.automation={scout:0,crew:0,rover:0,satellite:0,swarm:0,worldai:0,...(state.automation||{})};if(!Number.isFinite(state.manualClicks))state.manualClicks=state.explores||0;if(!Number.isFinite(state.autoLastSeen))state.autoLastSeen=Date.now();if(!state.enhancementVersion){state.score=Math.max(0,Math.round((state.score||0)*1000));state.explores=Math.max(state.manualClicks,Math.round((state.explores||0)*1000));}state.enhancementVersion=VERSION;}

function mutateBalance(){
  [12000,35000,75000,140000,240000,Infinity].forEach((n,i)=>STAGES[i].need=n);
  const bases=[{wood:120,stone:50},{wood:180,stone:80},{wood:500,stone:500,food:300},{wood:1200,stone:1600,knowledge:800}],scales=[1.34,1.36,1.40,1.44];BUILDINGS.forEach((b,i)=>{b.base=bases[i];b.scale=scales[i];});
  ACHIEVEMENTS[1].desc='手動で1,000回探索する';ACHIEVEMENTS[1].test=s=>s.manualClicks>=1000;ACHIEVEMENTS[2].desc='手動で10,000回探索する';ACHIEVEMENTS[2].test=s=>s.manualClicks>=10000;ACHIEVEMENTS[3].desc='建物を合計10回建てる';ACHIEVEMENTS[3].test=s=>buildingTotal(s)>=10;ACHIEVEMENTS[8].desc='人口1,000人を超える';ACHIEVEMENTS[8].test=s=>s.resources.population>=1000;ACHIEVEMENTS[9].desc='知識を2,500集める';ACHIEVEMENTS[9].test=s=>s.resources.knowledge>=2500;
  SPECIAL_EVENTS[0].choices=[['中へ入る','危険だが大きな発見があるかも',s=>chance(.62)?eventReward(s,{stone:120,knowledge:50},'洞窟の奥で大きな鉱脈を見つけた。'):penalty(s,{food:50},'迷って食料を大量に失った。')],['入口を調べる','安全に少しだけ調査する',s=>eventReward(s,{stone:50,knowledge:20},'入口周辺を慎重に調べた。')],['印だけ残す','資源は動かない',()=>logEvent('洞窟の位置だけ記録して撤退した。')]];
  SPECIAL_EVENTS[1].choices=[['こじ開ける','中身は完全にランダム',s=>{const r=Math.random();return r<.25?eventReward(s,{knowledge:140},'失われた研究データを発見した！'):r<.72?eventReward(s,{wood:100,stone:100},'大量の資材が入っていた。'):penalty(s,{food:40},'中身は腐っていた。');}],['研究所へ運ぶ','研究所Lv.1以上で効果大',s=>s.buildings.lab>0?eventReward(s,{knowledge:100},'研究所で安全に解析できた。'):eventReward(s,{knowledge:20},'設備不足で少しだけ解析した。')],['放置する','何も起こらない',()=>logEvent('怪しい箱には触れなかった。')]];
  SPECIAL_EVENTS[2].choices=[['迎え入れる','食料80 → 人口増加',s=>{if(s.resources.food>=80){s.resources.food-=80;s.resources.population+=applyGain('population',60,'event');return logEvent('食料を渡し、旅人たちを迎え入れた。');}return logEvent('食料不足で旅人たちは去っていった。');}],['交易する','木と石をまとめて獲得',s=>eventReward(s,{wood:70,stone:50},'旅人と交易して資材を得た。')],['話を聞く','知識を獲得',s=>eventReward(s,{knowledge:60},'遠い土地の知識を教えてもらった。')]];
  SPECIAL_EVENTS[3].choices=[['掘る','石を獲得。図鑑発見の可能性あり',s=>{eventReward(s,{stone:90},'地中から未知の構造物が現れた。');bonusDiscovery(.55);}],['観測する','知識を確実に獲得',s=>eventReward(s,{knowledge:70},'模様の周期性を記録した。')],['上で眠る','35%で大当たり',s=>chance(.35)?eventReward(s,{knowledge:120},'奇妙な夢から新しい理論を思いついた。'):logEvent('普通によく眠れた。')]];
}
function eventReward(s,obj,msg){Object.entries(obj).forEach(([k,v])=>s.resources[k]=(s.resources[k]||0)+applyGain(k,v,'event'));logEvent(msg);}
function bonusDiscovery(base=.02){const p=Math.min(.9,base*skillMods().discovery);if(!chance(p))return false;let pool=DISCOVERIES.filter(d=>d.stage<=state.stage&&!state.discovered.includes(d.id));if(!pool.length)return false;const d=pool[Math.floor(Math.random()*pool.length)];state.discovered.push(d.id);state.score+=700;logEvent(`図鑑登録：${d.name} ${d.icon}`);burst(`NEW! ${d.icon} ${d.name}`,'discovery',true);dopamine('discovery');return true;}

function installUI(){
  document.querySelectorAll('.resource').forEach((el,i)=>el.dataset.resource=KEYS[i]||'');const strip=document.querySelector('.resource-strip');if(strip&&!document.querySelector('.stats-strip'))strip.insertAdjacentHTML('afterend','<section class="stats-strip"><div><small>手動クリック</small><b id="manualCount">0</b></div><div class="accent-stat"><small>自動探索</small><b id="autoRate">0.0/秒</b></div><div><small>総探索数</small><b id="totalExplore">0</b></div></section>');
  const action=document.querySelector('.action-zone');if(action&&!document.getElementById('fxLayer'))action.insertAdjacentHTML('afterbegin','<div id="fxLayer" class="fx-layer" aria-live="polite"></div><div id="comboBadge" class="combo-badge hidden"></div>');
  const worldCard=document.querySelector('.world-card');if(worldCard&&!document.getElementById('burstLayer'))worldCard.insertAdjacentHTML('afterbegin','<div id="screenFlash" class="screen-flash"></div><div id="burstLayer" class="burst-layer" aria-live="polite"></div><div id="orbitScene" class="orbit-scene" aria-hidden="true"></div>');
  const planet=document.querySelector('.planet');if(planet&&!document.getElementById('planetScene'))planet.insertAdjacentHTML('beforeend','<div id="planetScene" class="planet-scene" aria-hidden="true"></div>');
  const tabs=document.querySelector('.tabs'),buildTab=tabs?.querySelector('[data-tab="build"]');if(tabs&&buildTab&&!tabs.querySelector('[data-tab="automation"]'))buildTab.insertAdjacentHTML('afterend','<button class="tab auto-tab" type="button" data-tab="automation">自動化 <span id="autoCount">0台</span></button>');
  const buildPanel=document.getElementById('buildPanel');if(buildPanel&&!document.getElementById('automationPanel'))buildPanel.insertAdjacentHTML('afterend','<section id="automationPanel" class="panel tab-panel"><div class="automation-summary"><div><small>現在の自動探索</small><strong id="autoRatePanel">0.0 探索/秒</strong></div><span>⚙️</span></div><div id="autoGrid" class="auto-grid"></div></section>');
  const modal=document.getElementById('choiceModal'),modalCard=modal?.querySelector('.modal-card');if(modal)modal.classList.add('event-modal');if(modalCard&&!document.getElementById('choiceResult'))modalCard.insertAdjacentHTML('beforeend','<div id="choiceResult" class="event-result hidden"></div>');
  const ver=document.querySelector('.version');if(ver)ver.textContent=`v${VERSION} · OFFLINE PWA`;const autoTab=tabs?.querySelector('[data-tab="automation"]');if(autoTab&&!autoTab.dataset.bound){autoTab.dataset.bound='1';autoTab.addEventListener('click',()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));autoTab.classList.add('active');document.getElementById('automationPanel').classList.add('active');});}
}

function injectStyle(){if(document.getElementById('mw-enhance-style'))return;const s=document.createElement('style');s.id='mw-enhance-style';s.textContent=`
.stats-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:10px}.stats-strip>div{background:rgba(255,255,255,.58);border:1px solid rgba(43,119,181,.1);border-radius:13px;padding:7px 8px;text-align:center}.stats-strip small{display:block;color:#6c86a3;font-size:8px}.stats-strip b{display:block;margin-top:2px;font-size:11px}.stats-strip .accent-stat{background:linear-gradient(135deg,rgba(221,252,238,.9),rgba(230,248,255,.92));border-color:rgba(41,182,111,.22)}.accent-stat b{color:#168d57}.tabs{grid-template-columns:repeat(4,1fr)!important}.tab{font-size:11px;padding-left:2px;padding-right:2px}.tab span{display:block;font-size:8px}.tab.auto-tab.active{color:#168d57}
.automation-summary{display:flex;align-items:center;justify-content:space-between;background:linear-gradient(135deg,#ecfff4,#eff9ff);border:1px solid rgba(41,182,111,.15);border-radius:16px;padding:10px 12px;margin-bottom:8px}.automation-summary small{display:block;color:#62809a;font-size:8px}.automation-summary strong{font-size:11px;color:#168d57}.automation-summary>span{font-size:24px}.auto-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.auto-card{border:1px solid rgba(50,121,175,.12);background:rgba(247,252,255,.92);border-radius:17px;padding:11px;text-align:left;min-height:132px}.auto-card.locked{filter:grayscale(.7);opacity:.58}.auto-card.can-build{border-color:rgba(38,169,108,.35);box-shadow:inset 0 0 0 1px rgba(38,169,108,.08)}.auto-head{display:flex;justify-content:space-between;align-items:center}.auto-icon{font-size:26px}.owned{font-size:10px;font-weight:900;background:#e9f6ff;padding:4px 7px;border-radius:999px}.auto-card h3{font-size:13px;margin:4px 0 2px}.auto-card p{font-size:9px;color:#6c86a3;margin:0 0 7px;line-height:1.45}.rate-pill{display:inline-block;background:#e7fff2;color:#148b54;font-weight:900;font-size:9px;border-radius:999px;padding:4px 7px;margin-bottom:5px}.auto-cost{font-size:9px;color:#5d7893}
.action-zone{position:relative;transition:.18s}.event-active .action-zone{visibility:hidden;pointer-events:none}.fx-layer{position:absolute;left:50%;top:24px;width:1px;height:1px;z-index:28;pointer-events:none}.float-gain{position:absolute;left:0;top:0;transform:translate(calc(-50% + var(--x,0px)),var(--y,0));font-size:16px;font-weight:1000;padding:5px 9px;border-radius:999px;background:rgba(255,255,255,.97);box-shadow:0 8px 24px rgba(30,91,138,.26),0 0 18px rgba(255,255,255,.8);animation:gainFly 1.25s cubic-bezier(.18,.8,.22,1) forwards;white-space:nowrap}.float-gain.gain{color:#0c9b57}.float-gain.loss{color:#e23f5a}.float-gain.auto-gain{background:rgba(224,255,241,.98)}.float-gain.big-gain{font-size:20px}.float-label{position:absolute;left:0;top:42px;transform:translateX(-50%);font-size:13px;font-weight:1000;white-space:nowrap;animation:labelPop 1s ease-out forwards}.float-label.manual{color:#fff;text-shadow:0 2px 8px rgba(0,55,130,.8)}.float-label.auto{color:#0b8350;background:rgba(255,255,255,.9);padding:3px 8px;border-radius:999px}.combo-badge{position:absolute;right:8px;top:-8px;z-index:29;color:#fff;font-weight:1000;font-size:14px;background:linear-gradient(135deg,#ff4fd8,#7e5cff,#20d9ff);padding:6px 10px;border-radius:999px;box-shadow:0 0 18px rgba(146,76,255,.55);animation:comboPulse .45s ease-out}
.resource.resource-flash{animation:resourceFlash .62s ease-out}.burst-layer{position:absolute;inset:0;pointer-events:none;z-index:24;display:grid;place-items:center}.center-burst{font-weight:1000;border-radius:20px;padding:11px 16px;background:rgba(255,255,255,.95);box-shadow:0 16px 40px rgba(22,77,120,.3),0 0 25px rgba(255,255,255,.8);animation:centerBurst 1.5s ease-out forwards;max-width:85%;text-align:center}.center-burst.event{color:#8b5bd6}.center-burst.result{color:#168d57}.center-burst.auto{color:#168d57}.center-burst.evolve{color:#1478e8;font-size:22px;background:linear-gradient(135deg,#fff,#dff7ff)}.center-burst.discovery{color:#9b52ff;font-size:18px;background:linear-gradient(135deg,#fff6ff,#e8fbff)}.screen-flash{position:absolute;inset:0;z-index:23;pointer-events:none;opacity:0;border-radius:28px}.screen-flash.flash{animation:screenFlash .5s ease-out}.world-card.dopamine{animation:worldPunch .52s ease-out}.world-card.mega{animation:worldMega .72s ease-out}.explore-btn.rush{box-shadow:0 0 0 4px rgba(255,255,255,.7),0 0 26px rgba(59,198,255,.9),0 16px 34px rgba(50,77,255,.36)}.fx-particle{position:absolute;z-index:30;pointer-events:none;font-size:var(--size,13px);left:var(--x);top:var(--y);animation:particleFly var(--dur,800ms) ease-out forwards;filter:drop-shadow(0 0 5px rgba(255,255,255,.9))}.shock-ring{position:absolute;left:50%;top:50%;width:30px;height:30px;border:3px solid rgba(255,255,255,.9);border-radius:50%;transform:translate(-50%,-50%);animation:shock .7s ease-out forwards;z-index:25;pointer-events:none}
.event-modal{align-items:flex-start!important;padding-top:max(70px,calc(env(safe-area-inset-top,0px) + 48px))!important;background:rgba(12,37,67,.58)!important}.event-modal .modal-card{max-height:calc(100dvh - 100px);overflow:auto;border:2px solid rgba(255,255,255,.9);box-shadow:0 30px 90px rgba(10,34,68,.48),0 0 0 1px rgba(99,190,255,.2)}.event-modal .choice-buttons{pointer-events:none;opacity:.45;transition:.22s}.event-modal.armed .choice-buttons{pointer-events:auto;opacity:1}.event-safe-note{font-size:9px;color:#708aa1;text-align:center;margin:0 0 9px}.event-result{border-top:1px solid rgba(50,121,175,.1);padding-top:12px}.event-result h3{margin:4px 0 6px;font-size:20px}.event-result p{font-size:12px;color:#536f88}.result-kicker{font-size:9px;letter-spacing:.16em;color:#1885e6;font-weight:900}.delta-row{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0 14px}.delta-chip{font-size:10px;font-weight:900;padding:6px 8px;border-radius:999px}.delta-chip.gain{background:#e6fff1;color:#12804d}.delta-chip.loss{background:#fff0f2;color:#c43f52}.delta-chip.neutral{background:#edf3f7;color:#6a8297}.result-close{width:100%;border:0;border-radius:14px;background:linear-gradient(135deg,#2fb0ff,#7b5cff);color:#fff;padding:13px;font-weight:1000;box-shadow:0 10px 24px rgba(68,104,230,.25)}
.discovery{position:relative;min-height:126px!important}.skill-badge{margin-top:5px;padding:4px 5px;border-radius:8px;background:linear-gradient(135deg,#eef7ff,#f5efff);font-size:7px;line-height:1.35;color:#586f9a;font-weight:800}.discovery.unknown .skill-badge{display:none}.discovery.got-skill{border-color:rgba(133,81,255,.22);box-shadow:inset 0 0 0 1px rgba(133,81,255,.06)}
.planet-scene{position:absolute;inset:0;pointer-events:none;z-index:8}.planet-asset{position:absolute;font-size:var(--s,18px);filter:drop-shadow(0 2px 2px rgba(18,58,90,.3));animation:assetPop .45s ease-out}.pa-house{left:31%;top:48%}.pa-house2{left:55%;top:56%}.pa-farm{left:18%;top:62%}.pa-farm2{left:65%;top:35%}.pa-lab{left:48%;top:33%}.pa-tower{left:69%;top:54%}.pa-rover{left:28%;top:34%;animation:roverMove 5s linear infinite}.pa-ai{left:43%;top:48%;font-size:28px;filter:drop-shadow(0 0 8px #7be9ff)}.orbit-scene{position:absolute;inset:0;z-index:7;pointer-events:none;overflow:hidden}.orbiter{position:absolute;filter:drop-shadow(0 4px 5px rgba(24,78,120,.35))}.ufo-1{font-size:30px;top:54px;left:-38px;animation:ufoFly 7s linear infinite}.ufo-2{font-size:22px;top:106px;right:-30px;animation:ufoFlyR 10s linear infinite}.satellite-1{font-size:25px;left:50%;top:50%;animation:satelliteOrbit 8s linear infinite;transform-origin:0 0}.drone-swarm{font-size:17px;right:30px;top:64px;animation:swarmFloat 2.6s ease-in-out infinite}.crew-flag{font-size:19px;left:26%;bottom:73px}.ai-aura{position:absolute;width:238px;height:238px;border:2px solid rgba(91,236,255,.65);border-radius:50%;left:50%;top:50%;transform:translate(-50%,-50%);box-shadow:0 0 22px rgba(91,236,255,.5),inset 0 0 25px rgba(91,236,255,.18);animation:auraPulse 2s ease-in-out infinite}
@keyframes gainFly{0%{opacity:0;transform:translate(calc(-50% + var(--x,0px)),calc(var(--y,0px) + 22px)) scale(.72)}18%{opacity:1;transform:translate(calc(-50% + var(--x,0px)),var(--y,0px)) scale(1.14)}100%{opacity:0;transform:translate(calc(-50% + var(--x,0px)),calc(var(--y,0px) - 92px)) scale(.92)}}@keyframes labelPop{0%{opacity:0;transform:translate(-50%,15px) scale(.8)}30%{opacity:1;transform:translate(-50%,0) scale(1.1)}100%{opacity:0;transform:translate(-50%,-48px) scale(.95)}}@keyframes centerBurst{0%{opacity:0;transform:scale(.55) rotate(-2deg)}15%{opacity:1;transform:scale(1.13) rotate(1deg)}70%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(.92)}}@keyframes resourceFlash{0%{transform:scale(1)}30%{transform:scale(1.12);background:#e4fff2;box-shadow:0 0 0 4px rgba(41,182,111,.15),0 0 22px rgba(50,255,165,.42)}100%{transform:scale(1)}}@keyframes comboPulse{0%{transform:scale(.7)}55%{transform:scale(1.16)}100%{transform:scale(1)}}@keyframes screenFlash{0%{opacity:.9;background:rgba(255,255,255,.85)}100%{opacity:0;background:rgba(87,194,255,.15)}}@keyframes worldPunch{0%{transform:scale(1)}35%{transform:scale(1.018);filter:saturate(1.4)}100%{transform:scale(1)}}@keyframes worldMega{0%{transform:scale(1)}25%{transform:scale(1.035);filter:saturate(1.8) brightness(1.08)}55%{transform:scale(.995)}100%{transform:scale(1)}}@keyframes particleFly{0%{opacity:0;transform:translate(0,0) scale(.6) rotate(0deg)}18%{opacity:1}100%{opacity:0;transform:translate(var(--dx),var(--dy)) scale(1.25) rotate(var(--rot,180deg))}}@keyframes shock{0%{opacity:1;transform:translate(-50%,-50%) scale(.3)}100%{opacity:0;transform:translate(-50%,-50%) scale(9)}}@keyframes assetPop{0%{opacity:0;transform:scale(.2)}65%{opacity:1;transform:scale(1.18)}100%{transform:scale(1)}}@keyframes roverMove{0%,100%{transform:translateX(-10px)}50%{transform:translateX(34px)}}@keyframes ufoFly{0%{transform:translateX(0) rotate(-4deg)}100%{transform:translateX(520px) rotate(4deg)}}@keyframes ufoFlyR{0%{transform:translateX(0) rotate(4deg)}100%{transform:translateX(-520px) rotate(-4deg)}}@keyframes satelliteOrbit{from{transform:rotate(0deg) translateX(132px) rotate(0deg)}to{transform:rotate(360deg) translateX(132px) rotate(-360deg)}}@keyframes swarmFloat{50%{transform:translateY(-10px) rotate(4deg)}}@keyframes auraPulse{50%{transform:translate(-50%,-50%) scale(1.05);opacity:.55}}
@media(min-width:700px){.auto-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:380px){.tab{font-size:9px}.auto-card{padding:9px}.discovery{min-height:118px!important}.skill-badge{font-size:6px}}@media(prefers-reduced-motion:reduce){.float-gain,.float-label,.center-burst,.resource.resource-flash,.fx-particle,.shock-ring,.world-card,.planet-asset,.orbiter,.ai-aura{animation:none!important}}
`;document.head.appendChild(s);}

function emit(delta,isAuto=false,big=false){const fx=document.getElementById('fxLayer');if(!fx)return;let i=0;Object.entries(delta).forEach(([k,v])=>{const el=document.createElement('div');el.className=`float-gain ${v<0?'loss':'gain'} ${isAuto?'auto-gain':''} ${big?'big-gain':''}`;el.textContent=`${META[k].icon} ${v>0?'+':''}${fmt2(v)}`;el.style.setProperty('--x',`${(i-1.5)*54+(Math.random()*30-15)}px`);el.style.setProperty('--y',`${Math.random()*18-4}px`);fx.appendChild(el);setTimeout(()=>el.remove(),1300);i++;const card=document.querySelector(`[data-resource="${k}"]`);if(card){card.classList.remove('resource-flash');void card.offsetWidth;card.classList.add('resource-flash');}});}
function floatLabel(text,type='manual'){const fx=document.getElementById('fxLayer');if(!fx)return;const el=document.createElement('div');el.className=`float-label ${type}`;el.textContent=text;fx.appendChild(el);setTimeout(()=>el.remove(),1050);}
function burst(text,type='event',mega=false){const host=document.getElementById('burstLayer');if(!host)return;const el=document.createElement('div');el.className=`center-burst ${type}`;el.textContent=text;host.appendChild(el);setTimeout(()=>el.remove(),1600);if(mega)dopamine(type,true);}
function particles(count=10,emoji='✦'){const host=document.querySelector('.world-card');if(!host)return;for(let i=0;i<Math.min(count,30);i++){const p=document.createElement('span');p.className='fx-particle';p.textContent=i%4===0?'◆':emoji;p.style.setProperty('--x',`${35+Math.random()*30}%`);p.style.setProperty('--y',`${36+Math.random()*25}%`);p.style.setProperty('--dx',`${(Math.random()-.5)*260}px`);p.style.setProperty('--dy',`${-70-Math.random()*160}px`);p.style.setProperty('--rot',`${(Math.random()-.5)*540}deg`);p.style.setProperty('--size',`${9+Math.random()*12}px`);p.style.setProperty('--dur',`${650+Math.random()*500}ms`);host.appendChild(p);setTimeout(()=>p.remove(),1300);}}
function dopamine(type='click',mega=false){const card=document.querySelector('.world-card'),flash=document.getElementById('screenFlash');if(!card)return;card.classList.remove('dopamine','mega');void card.offsetWidth;card.classList.add(mega?'mega':'dopamine');if(flash){flash.classList.remove('flash');void flash.offsetWidth;flash.classList.add('flash');}const ring=document.createElement('div');ring.className='shock-ring';card.appendChild(ring);setTimeout(()=>ring.remove(),760);particles(mega?24:8,type==='discovery'?'✦':type==='build'?'◆':'•');setTimeout(()=>card.classList.remove('dopamine','mega'),800);}
function updateCombo(){const now=performance.now();combo=now-lastManualAt<420?Math.min(combo+1,999):1;lastManualAt=now;const badge=document.getElementById('comboBadge');if(!badge)return;badge.textContent=combo>=10?`RUSH ×${combo}`:`×${combo}`;badge.classList.toggle('hidden',combo<3);badge.classList.remove('combo-badge');void badge.offsetWidth;badge.classList.add('combo-badge');const btn=document.getElementById('exploreBtn');btn.classList.toggle('rush',combo>=10);if(combo===10||combo===25||combo===50||combo===100||combo%250===0){burst(`RUSH ×${combo}!`,'evolve',true);beep(780,.05);setTimeout(()=>beep(980,.06),70);}}

function enhancedExplore(){if(eventLocked||!document.getElementById('choiceModal').classList.contains('hidden'))return;ensureState();const before=snap();state.explores++;state.manualClicks++;state.score++;const r=Math.random(),farm=state.buildings.farm,lab=state.buildings.lab;let key,n,msg;if(r<.30){key='wood';n=applyGain(key,randomInt(2,5)+Math.floor(state.stage*.6),'manual');}else if(r<.54){key='stone';n=applyGain(key,randomInt(1,4)+Math.floor(state.stage*.5),'manual');}else if(r<.73){key='food';n=applyGain(key,randomInt(2,5)+farm,'manual');}else if(r<.88){key='knowledge';n=applyGain(key,randomInt(1,3)+Math.ceil(lab*.7),'manual');}else{key='population';n=applyGain(key,1+Math.floor(state.buildings.house/2),'manual');}state.resources[key]+=n;msg=`${META[key].label} +${n}`;logEvent(`手動探索：${msg}`);tryDiscovery(false);bonusDiscovery(.008);updateStage();checkAchievements();saveState();render();animateExplore();emit(diff(before));floatLabel('+1 探索');updateCombo();dopamine('click',combo>=25);beep(390+Math.min(combo,80)*2,.035);const specialRate=(.045+state.buildings.tower*.004)*skillMods().eventRate;if(state.manualClicks>=8&&chance(Math.min(.35,specialRate)))setTimeout(()=>showSpecialEvent(),180);}
function processAuto(count,offline=false){count=Math.floor(count);if(count<=0)return{};const before=snap(),farm=state.buildings.farm,lab=state.buildings.lab,house=state.buildings.house,st=state.stage;state.explores+=count;state.score+=count;const j=(k,m)=>applyGain(k,Math.max(0,Math.round(m*(.94+Math.random()*.12))));state.resources.wood+=j('wood',count*.30*(3.5+st*.6));state.resources.stone+=j('stone',count*.24*(2.5+st*.5));state.resources.food+=j('food',count*.19*(3.5+farm));state.resources.knowledge+=j('knowledge',count*.15*(2+lab*.7));state.resources.population+=j('population',count*.12*(1+Math.floor(house/2)));if(chance(1-Math.pow(.99,Math.min(count,400))))tryDiscovery(false);bonusDiscovery(Math.min(.12,count*.00005));updateStage();checkAchievements();const d=diff(before);if(!offline){const now=Date.now();if(now-lastAutoFx>1050){emit(d,true,count>=100);floatLabel(`AUTO ×${fmt2(count)}`,'auto');if(count>=250)dopamine('auto',count>=1000);lastAutoFx=now;}}return d;}
function buyAuto(id){ensureState();const a=AUTO_ITEMS.find(x=>x.id===id);if(!a||state.stage<a.unlock)return;const c=scaledCost(a);if(!afford(c)){toast('資源が足りない');beep(170,.05);return;}const before=snap();Object.entries(c).forEach(([k,v])=>state.resources[k]-=v);state.automation[id]++;logEvent(`${a.name} 導入：+${a.rate}/秒`);saveState();render();emit(diff(before));burst(`${a.icon} ${a.name} 配備!`,'auto',true);beep(540,.06);setTimeout(()=>beep(720,.07),70);}
function renderAuto(){const grid=document.getElementById('autoGrid');if(!grid)return;grid.innerHTML='';AUTO_ITEMS.forEach(a=>{const locked=state.stage<a.unlock,c=scaledCost(a),ok=afford(c),owned=state.automation[a.id]||0;const b=document.createElement('button');b.type='button';b.disabled=locked;b.className=`auto-card ${locked?'locked':''} ${!locked&&ok?'can-build':''}`;b.innerHTML=`<div class="auto-head"><span class="auto-icon">${locked?'🔒':a.icon}</span><span class="owned">×${owned}</span></div><h3>${a.name}</h3><p>${locked?`${STAGES[a.unlock].name}で解放`:a.desc}</p><div class="rate-pill">${locked?'???':`+${a.rate}/秒`}</div><div class="auto-cost">${locked?'???':costText2(c)}</div>`;b.addEventListener('click',()=>buyAuto(a.id));grid.appendChild(b);});}
function renderDiscoverySkills(){document.querySelectorAll('#discoveryGrid .discovery').forEach((el,i)=>{const d=DISCOVERIES[i],got=state.discovered.includes(d.id),s=SKILLS[d.id];if(!got||!s)return;el.classList.add('got-skill');const badge=document.createElement('div');badge.className='skill-badge';badge.innerHTML=`⚡ ${s.name}<br>${s.desc}`;el.appendChild(badge);});}
function renderWorldAssets(){const p=document.getElementById('planetScene'),o=document.getElementById('orbitScene');if(!p||!o)return;p.innerHTML='';o.innerHTML='';const addP=(cls,icon)=>p.insertAdjacentHTML('beforeend',`<span class="planet-asset ${cls}">${icon}</span>`),addO=(cls,icon)=>o.insertAdjacentHTML('beforeend',`<span class="orbiter ${cls}">${icon}</span>`);const b=state.buildings,a=state.automation;if(b.house>0)addP('pa-house','🏠');if(b.house>=3)addP('pa-house2','🏘️');if(b.farm>0)addP('pa-farm','🌾');if(b.farm>=3)addP('pa-farm2','🌻');if(b.lab>0)addP('pa-lab','🧪');if(b.tower>0)addP('pa-tower','🔭');if(a.rover>0)addP('pa-rover','🤖');if(a.worldai>0){addP('pa-ai','◇');o.insertAdjacentHTML('beforeend','<span class="ai-aura"></span>');}if(a.scout>0)addO('ufo-1','🛸');if(a.scout>=5)addO('ufo-2','🛸');if(a.satellite>0)addO('satellite-1','🛰️');if(a.swarm>0)addO('drone-swarm','✦ ✦ ✦');if(a.crew>0)addO('crew-flag','🚩');}

const originalRender=render,originalBuild=build;
function enhancedBuild(id){const beforeLevel=state.buildings[id]||0,before=snap();originalBuild(id);if((state.buildings[id]||0)>beforeLevel){emit(diff(before),false,true);const found=BUILDINGS.find(b=>b.id===id);burst(`${found?.icon||'◆'} 建設完了!`,'evolve',true);renderWorldAssets();beep(520,.05);setTimeout(()=>beep(700,.06),65);}}
function enhancedRender(){ensureState();originalRender();document.getElementById('manualCount').textContent=fmt2(state.manualClicks);const rr=rate();document.getElementById('autoRate').textContent=`${rr<10?rr.toFixed(1):fmt2(rr)}/秒`;document.getElementById('totalExplore').textContent=fmt2(state.explores);document.getElementById('autoCount').textContent=`${totalAuto()}台`;document.getElementById('autoRatePanel').textContent=`現在 ${rr<10?rr.toFixed(1):fmt2(rr)} 探索/秒`;document.getElementById('levelBadge').textContent=`Lv.${1+Math.floor(state.score/1000)}`;renderAuto();renderDiscoverySkills();renderWorldAssets();}
function setEventLock(on){eventLocked=on;document.body.classList.toggle('event-active',on);const btn=document.getElementById('exploreBtn');if(btn){btn.disabled=on;btn.setAttribute('aria-disabled',on?'true':'false');}if(!on){combo=0;btn?.classList.remove('rush');document.getElementById('comboBadge')?.classList.add('hidden');}}
function enhancedShowEvent(){const modal=document.getElementById('choiceModal');if(!modal.classList.contains('hidden'))return;setEventLock(true);modal.classList.remove('armed');const ev=SPECIAL_EVENTS[Math.floor(Math.random()*SPECIAL_EVENTS.length)];document.getElementById('choiceTitle').textContent=ev.title;document.getElementById('choiceText').textContent=ev.text;const result=document.getElementById('choiceResult');result.classList.add('hidden');const box=document.getElementById('choiceButtons');box.classList.remove('hidden');box.innerHTML='<div class="event-safe-note">連打の誤操作防止のため、選択肢は少し待ってから有効になります</div>';ev.choices.forEach(([name,desc,fn])=>{const btn=document.createElement('button');btn.className='choice-btn';btn.type='button';btn.innerHTML=`${name}<small>${desc}</small>`;btn.addEventListener('click',()=>{if(!modal.classList.contains('armed'))return;modal.classList.remove('armed');const before=snap(),logBefore=state.log[0]?.m||'';fn(state);const progress=50*(1+state.buildings.tower);state.score+=progress;updateStage();checkAchievements();saveState();render();const d=diff(before),msg=state.log[0]?.m||logBefore||'特に何も起こらなかった。';const chips=Object.entries(d).map(([k,v])=>`<span class="delta-chip ${v<0?'loss':'gain'}">${META[k].icon} ${v>0?'+':''}${fmt2(v)}</span>`).join('');result.innerHTML=`<div class="result-kicker">選択結果</div><h3>${escapeHtml(name)}</h3><p>${escapeHtml(msg)}</p><div class="delta-row">${chips||'<span class="delta-chip neutral">資源変化なし</span>'}<span class="delta-chip gain">◈ 進行 +${fmt2(progress)}</span></div><button class="result-close" type="button">結果を確認した</button>`;box.classList.add('hidden');result.classList.remove('hidden');emit(d,false,true);burst('EVENT RESULT!','result',true);document.getElementById('eventMessage').textContent=`イベント結果：${msg}`;result.querySelector('.result-close').addEventListener('click',()=>{modal.classList.add('hidden');setEventLock(false);});beep(600,.06);setTimeout(()=>beep(820,.07),80);});box.appendChild(btn);});modal.classList.remove('hidden');burst('⚠ SPECIAL EVENT','event',true);setTimeout(()=>{if(!modal.classList.contains('hidden'))modal.classList.add('armed');},700);}
function applyAutoOffline(){ensureState();const m=skillMods(),now=Date.now(),elapsed=Math.min(8*3600000,Math.max(0,now-state.autoLastSeen)),seconds=Math.floor(elapsed/1000),count=Math.floor(rate()*seconds*m.offline);if(count>0){const d=processAuto(count,true);logEvent(`留守中：AUTO探索 ×${fmt2(count)}`);setTimeout(()=>{toast(`留守中に ${fmt2(count)} 回探索`);emit(d,true,true);},450);}state.autoLastSeen=now;saveState();}
function startAuto(){if(autoTimer)clearInterval(autoTimer);lastTick=performance.now();autoTimer=setInterval(()=>{const now=performance.now(),dt=Math.min(2,(now-lastTick)/1000);lastTick=now;const r=rate();if(r<=0)return;autoCarry+=r*dt;const n=Math.floor(autoCarry);if(n<=0)return;autoCarry-=n;processAuto(Math.min(n,250000));state.autoLastSeen=Date.now();saveState();render();},500);}

injectStyle();installUI();mutateBalance();ensureState();explore=enhancedExplore;showSpecialEvent=enhancedShowEvent;render=enhancedRender;build=enhancedBuild;document.getElementById('exploreBtn').onclick=enhancedExplore;applyAutoOffline();render();saveState();startAuto();window.addEventListener('pagehide',()=>{state.autoLastSeen=Date.now();saveState();});
})();